### ISSUE TITLE
Stability information

### ISSUE THREAD

**Issue by marek-obuchowicz** [spulec/PyQS#38]
Could you please provide more information about stability / maturity of the library? `It can do anything up to and including eating your laundry.` sounds actually very unclear about what to expect about PyQS. It would be more helpful if potential users could read that part xxx seems to work fine, part xxx is under heavy development and part zzzz is completely missing yet.

**Comment by andrewgross** [comment]
Hey Marek,

Happy to discuss.  At the moment we have been running PyQS in production for about a year now with no issues.  The library is not under heavy development at the moment since it has worked extremely well for our use case.  At the moment the biggest missing feature is python3 support, which can be worked on if there is demand.

The API should be very stable and we have no plans for changing it right now.

**Comment by andrewgross** [comment]
I have updated the README to make the **WARNING** more informative

**Comment by marek-obuchowicz** [comment]
👍 Thanks a lot!
That would be clear for us now that we can use this library for prototype project

**Comment by spulec** [comment]
Going to close. Feel free to reopen if you need more info.
