### ISSUE TITLE
Document test differences between MacOS and Travis

### ISSUE THREAD

**Issue by andrewgross** [spulec/PyQS#66]
Recording this for posterity.  The test for `Test managing process replaces reader children` would succeed in my local MacOS but fail in Travis, as seen below.

https://travis-ci.org/spulec/PyQS/jobs/608285247

The underlying issue was that we were only waiting `0.1` seconds to see if the ReadWorker would shut down, but the ReadWorker was instructed to wait for up to 20 seconds to see if there were messages available in SQS.  Obviously, `20 > 0.1` so this should fail.  We fixed it by setting the `LONG_POLLING_INTERVAL` to `1`, and the wait time to `2` seconds.  

However, this does not answer the question as to why this test succeeded locally on MacOS before the fix.  This ticket is to remind our future selves of this non sequitur in case we have similar issues or the inexplicable inclination to debug the depths of the underlying issue.

**Comment by spulec** [comment]
So it looks like this was due to a timing issue. On MacOS, the `shutdown()` for the worker is getting called before the subprocess is actually started up. This results in the `while not self.should_exit.is_set() and self.parent_is_alive():` loop being skipped the first time and `read_message()` never being called. I'm guessing on travis/linux the subprocess is able to start quicker.

During real usage, I think this is fine. The only problems I can think of this causing are basically what we ran into. Going to close, but let me know if you have other ideas.
